"""Unit tests for the gd support library and the small tools (no Godot needed).
Run: python3 -m unittest discover -s tools/py/tests -v"""
from __future__ import annotations

import contextlib
import gzip
import io
import json
import os
import subprocess
import sys
import tarfile
import tempfile
import textwrap
import time
import unittest
from pathlib import Path

HERE = Path(__file__).resolve().parent
PY = HERE.parent
sys.path.insert(0, str(PY))

from gdlib import docs, env, linuxrun, locks, snapshot, tracking  # noqa: E402
import package_linux  # noqa: E402
import sync_bible  # noqa: E402
import xplat_determinism  # noqa: E402


class TestRWLock(unittest.TestCase):
    def run_py(self, code: str, tmp: Path) -> subprocess.Popen:
        prelude = f"import sys, time; sys.path.insert(0, {str(PY)!r}); from gdlib import locks; from pathlib import Path; L = locks.RWLock(Path({str(tmp)!r}))\n"
        return subprocess.Popen([sys.executable, "-c", prelude + code], stdout=subprocess.PIPE, text=True)

    def test_shared_holders_overlap(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            tmp = Path(d)
            code = "with L.shared():\n    print('in', flush=True); time.sleep(0.8)\n"
            procs = [self.run_py(code, tmp) for _ in range(3)]
            t0 = time.time()
            for p in procs:
                self.assertEqual(p.stdout.readline().strip(), "in")
            self.assertLess(time.time() - t0, 0.7, "three shared holders must be inside at the same time")
            for p in procs:
                p.wait()
                p.stdout.close()

    def test_exclusive_excludes_shared(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            tmp = Path(d)
            holder = self.run_py("with L.exclusive('test'):\n    print('locked', flush=True); time.sleep(1.0)\n", tmp)
            self.assertEqual(holder.stdout.readline().strip(), "locked")
            t0 = time.time()
            with locks.RWLock(tmp).shared():
                waited = time.time() - t0
            holder.wait()
            holder.stdout.close()
            self.assertGreater(waited, 0.6, "shared must wait for the exclusive holder")

    def test_waiting_importer_is_not_starved_by_new_readers(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            tmp = Path(d)
            reader = self.run_py("with L.shared():\n    print('r', flush=True); time.sleep(1.5)\n", tmp)
            self.assertEqual(reader.stdout.readline().strip(), "r")
            t0 = time.time()
            writer = self.run_py("with L.exclusive():\n    print('w', time.time(), flush=True); time.sleep(0.2)\n", tmp)
            time.sleep(0.4)  # the writer is now queued behind the running reader
            late = self.run_py("with L.shared():\n    print('l', time.time(), flush=True)\n", tmp)
            w = float(writer.stdout.readline().split()[1])
            l_ = float(late.stdout.readline().split()[1])
            for p in (reader, writer, late):
                p.wait()
                p.stdout.close()
            self.assertLess(w, l_, "a reader that arrives after a queued writer must not overtake it")
            self.assertGreater(w - t0, 1.2, "writer had to wait for the running reader")


class TestTracking(unittest.TestCase):
    def test_snapshot_reacts_only_to_what_the_import_cache_needs(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            game = Path(d)
            (game / "src").mkdir()
            cache = game.parent / "sig.json"
            klass = game / "src" / "a.gd"
            klass.write_text("class_name Alpha\nextends RefCounted\n\nfunc f() -> int:\n\treturn 1\n")
            plain = game / "src" / "plain.gd"
            plain.write_text("extends RefCounted\n")
            base = tracking.snapshot(game, cache)
            self.assertEqual(sorted(base), ["src/a.gd"], "scripts without class_name are irrelevant to the class cache")
            (game / "src" / "a.gd.uid").write_text("uid://x")             # generated by the editor: ignored
            (game / ".godot").mkdir()
            (game / ".godot" / "junk.tscn").write_text("x")               # cache dir: ignored
            (game / "notes.md").write_text("x")                           # untracked extension
            self.assertEqual(tracking.snapshot(game, cache), base)
            klass.write_text("class_name Alpha\nextends RefCounted\n\nfunc f() -> int:\n\treturn 2  # body edit\n")
            self.assertEqual(tracking.snapshot(game, cache), base, "a body-only edit needs no import")
            plain.write_text("extends RefCounted\nfunc g() -> void:\n\tpass\n")
            self.assertEqual(tracking.snapshot(game, cache), base, "neither does editing a script without class_name")
            klass.write_text("class_name Alpha\nextends Node\n")
            changed = tracking.snapshot(game, cache)
            self.assertNotEqual(changed, base, "a changed `extends` header does")
            klass.write_text("class_name Beta\nextends Node\n")
            self.assertNotEqual(tracking.snapshot(game, cache), changed, "so does a rename")
            (game / "src" / "b.gd").write_text("class_name Gamma\n")
            self.assertIn("src/b.gd", tracking.snapshot(game, cache))
            (game / "src" / "b.gd").unlink()
            self.assertNotIn("src/b.gd", tracking.snapshot(game, cache))  # deletions count too
            scene = game / "src" / "s.tscn"
            scene.write_text("[gd_scene]\n")
            s1 = tracking.snapshot(game, cache)
            scene.write_text("[gd_scene]\n# edited\n")
            self.assertNotEqual(tracking.snapshot(game, cache), s1, "scenes/assets are tracked by mtime+size")

    def test_import_state_staleness_and_reason(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            game = Path(d) / "game"
            (game / ".godot").mkdir(parents=True)
            (game / "x.gd").write_text("class_name X\n")
            binary = Path(d) / "godot"
            binary.write_text("bin")
            st = tracking.ImportState(Path(d) / "state.json", game, binary)
            self.assertTrue(st.is_stale()[0])
            st.save(st.snapshot(), 0.1)
            self.assertTrue(st.is_stale()[0], "class cache file missing -> stale")
            (game / ".godot" / "global_script_class_cache.cfg").write_text("list=[]")
            self.assertEqual(st.is_stale(), (False, "up to date"))
            (game / "x.gd").write_text("class_name X\n# body\n")
            self.assertEqual(st.is_stale(), (False, "up to date"))
            (game / "y.gd").write_text("class_name Y\n")
            stale, why = st.is_stale()
            self.assertTrue(stale)
            self.assertIn("new: y.gd", why)


class TestEnvPaths(unittest.TestCase):
    def test_to_res_path(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            old = env.GAME
            env.GAME = Path(d).resolve()
            try:
                self.assertEqual(env.to_res_path("res://src/a.gd"), "res://src/a.gd")
                self.assertEqual(env.to_res_path("src/a.gd"), "res://src/a.gd")
                self.assertEqual(env.to_res_path("game/src/a.gd"), "res://src/a.gd")
                self.assertEqual(env.to_res_path(str(env.GAME / "src" / "a.gd")), "res://src/a.gd")
                self.assertEqual(env.to_res_path("game"), "res://")
            finally:
                env.GAME = old


class TestDocs(unittest.TestCase):
    def test_index_and_member_lookup(self) -> None:
        idx = docs.class_index()
        for name in ("Node", "Vector2i", "@GlobalScope", "@GDScript", "Logger", "ENetMultiplayerPeer", "RegEx"):
            self.assertIn(name, idx)
        self.assertEqual(docs.resolve_class_name("node2d"), "Node2D")
        self.assertIn("CanvasItem", docs.ancestry("Node2D"))
        self.assertTrue(docs.find_members("Node2D", "position"))
        self.assertTrue(docs.find_members("Node2D", "queue_free"))          # inherited from Node
        self.assertTrue(docs.find_members("@GlobalScope", "roundi"))
        self.assertFalse(docs.find_members("Node", "definitely_not_a_member"))
        sig = docs.method_signature(docs.find_members("Node", "add_child")[0][2])
        self.assertIn("add_child(node: Node", sig)


class TestSyncBible(unittest.TestCase):
    def test_copy_refuse_force_and_check(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            src, dst = Path(d) / "in", Path(d) / "out"
            src.mkdir()
            for n in sync_bible.FILES:
                (src / n).write_text(json.dumps({"name": n}))
            old = (sync_bible.SRC_DIR, sync_bible.DST_DIR)
            sync_bible.SRC_DIR, sync_bible.DST_DIR = src, dst
            quiet = contextlib.ExitStack()
            quiet.enter_context(contextlib.redirect_stdout(io.StringIO()))
            quiet.enter_context(contextlib.redirect_stderr(io.StringIO()))
            try:
                self.assertEqual(sync_bible.sync(False), 0)
                self.assertEqual(sync_bible.check(), 0)
                for n in sync_bible.FILES:
                    self.assertEqual((src / n).read_bytes(), (dst / n).read_bytes())
                self.assertTrue((dst / "README.md").read_text().startswith("# game/data/bible - GENERATED, DO NOT EDIT"))
                (dst / sync_bible.FILES[0]).write_text("hand edit")
                self.assertEqual(sync_bible.check(), 1)
                self.assertEqual(sync_bible.sync(False), 1, "must refuse to clobber a hand edit")
                self.assertEqual((dst / sync_bible.FILES[0]).read_text(), "hand edit")
                self.assertEqual(sync_bible.sync(True), 0)
                self.assertEqual(sync_bible.check(), 0)
                (src / sync_bible.FILES[1]).write_text("changed upstream")
                self.assertEqual(sync_bible.check(), 1, "stale mirror must be detected")
                self.assertEqual(sync_bible.sync(False), 0, "an untouched mirror follows Input/")
            finally:
                quiet.close()
                sync_bible.SRC_DIR, sync_bible.DST_DIR = old


class TestSnapshotRules(unittest.TestCase):
    def test_exclusions(self) -> None:
        for rel in ("tools/godot", "tools/godot-linux-x86_64", "tools/godot_docs", ".cache", ".backups", "builds", "game/.godot",
                    "prototypes/ui/.godot", "tools/py/__pycache__"):
            self.assertTrue(snapshot.excluded_dir(rel), rel)
        for rel in ("tools/py", "game/src", "docs", "Input", "prototypes/ui", "tools/docker"):
            self.assertFalse(snapshot.excluded_dir(rel), rel)


class TestXplatCompare(unittest.TestCase):
    def test_identical_and_divergent(self) -> None:
        a = [(20, "aa"), (40, "bb"), (60, "cc")]
        self.assertIsNone(xplat_determinism.compare({"mac": a, "linux": list(a)}))
        b = [(20, "aa"), (40, "bb"), (60, "XX")]
        msg = xplat_determinism.compare({"mac": a, "linux": b})
        self.assertIn("tick 60", msg)
        self.assertIn("last tick where all targets agreed: 40", msg)
        short = xplat_determinism.compare({"mac": a, "linux": a[:2]})
        self.assertIn("chain ended earlier", short)

    def test_parse_chain(self) -> None:
        text = "noise\nHASH tick=20 DEADbeef\nHASH tick=40 01\nSCENARIO_DONE\n"
        self.assertEqual(xplat_determinism.parse_chain(text), [(20, "deadbeef"), (40, "01")])


class TestLinuxSync(unittest.TestCase):
    def test_mirror_copy_delete_and_keep_godot(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            src, dst = Path(d) / "src", Path(d) / "dst"
            (src / "a").mkdir(parents=True)
            (src / "a" / "x.gd").write_text("1")
            (src / ".godot").mkdir()
            (src / ".godot" / "host_cache").write_text("host")
            copied, deleted, total = linuxrun.sync_tree(src, dst)
            self.assertEqual((copied, deleted, total), (1, 0, 1))
            self.assertFalse((dst / ".godot").exists(), "host .godot must never be mirrored")
            (dst / ".godot").mkdir()
            (dst / ".godot" / "linux_cache").write_text("keep")
            (dst / "stale.gd").write_text("gone from source")
            (src / "a" / "x.gd").write_text("22")
            copied, deleted, _ = linuxrun.sync_tree(src, dst)
            self.assertEqual((copied, deleted), (1, 1))
            self.assertEqual((dst / "a" / "x.gd").read_text(), "22")
            self.assertFalse((dst / "stale.gd").exists())
            self.assertTrue((dst / ".godot" / "linux_cache").exists(), "the container's own .godot survives a sync")
            self.assertEqual(linuxrun.sync_tree(src, dst)[:2], (0, 0), "second sync is a no-op")


class TestLinuxShotRewrite(unittest.TestCase):
    def test_out_path_is_redirected_into_the_mounted_cache(self) -> None:
        toks, host, inside = linuxrun._rewrite_shot(["shot", "res://a.tscn", "/tmp/x/out.png", "--frames", "5", "--", "--seed=1"])
        self.assertEqual(host, Path("/tmp/x/out.png").resolve())
        self.assertEqual(inside, "/work/.cache/shot_out/out.png")
        self.assertEqual(toks, ["shot", "res://a.tscn", inside, "--frames", "5", "--", "--seed=1"])
        toks, host, _ = linuxrun._rewrite_shot(["shot", "--size", "800x450", "res://a.tscn", "o.png"])
        self.assertIsNotNone(host)
        self.assertTrue(toks[4].endswith("/o.png"))
        self.assertEqual(linuxrun._rewrite_shot(["test", "fp"]), (["test", "fp"], None, ""))


class TestDebPackage(unittest.TestCase):
    def test_deb_structure(self) -> None:
        with tempfile.TemporaryDirectory() as d:
            deb = Path(d) / "x.deb"
            payload = {"opt/meridian-fracture/MeridianFracture.x86_64": (b"\x7fELF-binary", 0o755),
                       "opt/meridian-fracture/MeridianFracture.pck": (b"pck", 0o644),
                       "usr/share/applications/meridian-fracture.desktop": (package_linux.DESKTOP.encode(), 0o644)}
            package_linux.build_deb(deb, "9.9.9", payload)
            blob = deb.read_bytes()
            self.assertTrue(blob.startswith(b"!<arch>\n"))
            members, pos = {}, 8
            order = []
            while pos < len(blob):
                hdr = blob[pos:pos + 60]
                name = hdr[:16].decode().strip().rstrip("/")
                size = int(hdr[48:58].decode().strip())
                self.assertEqual(hdr[58:60], b"`\n")
                members[name] = blob[pos + 60:pos + 60 + size]
                order.append(name)
                pos += 60 + size + (size % 2)
            self.assertEqual(order, ["debian-binary", "control.tar.gz", "data.tar.gz"])
            self.assertEqual(members["debian-binary"], b"2.0\n")
            with tarfile.open(fileobj=io.BytesIO(members["control.tar.gz"])) as tf:
                control = tf.extractfile("./control").read().decode()
                self.assertIn("Package: meridian-fracture", control)
                self.assertIn("Version: 9.9.9", control)
                self.assertIn("Architecture: amd64", control)
                self.assertEqual(tf.getmember("./postinst").mode, 0o755)
            with tarfile.open(fileobj=io.BytesIO(members["data.tar.gz"])) as tf:
                names = tf.getnames()
                self.assertIn("./opt/meridian-fracture/MeridianFracture.x86_64", names)
                self.assertEqual(tf.getmember("./opt/meridian-fracture/MeridianFracture.x86_64").mode, 0o755)
                link = tf.getmember("./usr/bin/meridian-fracture")
                self.assertTrue(link.issym())
                self.assertEqual(link.linkname, "/opt/meridian-fracture/MeridianFracture.x86_64")
                self.assertEqual(tf.getmember("./opt/meridian-fracture/MeridianFracture.pck").uname, "root")

    def test_icon_is_a_valid_png(self) -> None:
        png = package_linux.make_icon(64)
        self.assertTrue(png.startswith(b"\x89PNG\r\n\x1a\n"))
        self.assertTrue(png.endswith(b"IEND\xaeB`\x82"))


if __name__ == "__main__":
    unittest.main()
