"""provenance.py - provenance.json (schema fixed by qa.md 7.8) and NOTICE.txt, generated from the manifest.

One entry per shipped OGG, sorted by `file`.  `created_utc` is copied from the previous file while the OGG's bytes are
unchanged and stamped only when the bytes change (so regenerating an unchanged recipe leaves the file byte-identical);
`SOURCE_DATE_EPOCH` overrides the clock (reproducible fresh builds)."""
from __future__ import annotations

import datetime as dt
import os

import dsp

REL = "game/assets/audio/"
LICENCE_TOOLS = ["BSD-3-Clause (numpy, soundfile)", "LGPL-2.1 (libsndfile, build-time only)", "BSD-3-Clause (libvorbis, build-time only)"]


def _now() -> str:
    sde = os.environ.get("SOURCE_DATE_EPOCH")
    t = dt.datetime.fromtimestamp(int(sde), dt.timezone.utc) if sde else dt.datetime.now(dt.timezone.utc)
    return t.strftime("%Y-%m-%dT%H:%M:%SZ")


def build(assets: dict, prev: dict, gen: dict) -> dict:
    old = {e["file"]: e for e in prev.get("files", [])}
    versions = {k: gen[k] for k in ("python", "numpy", "soundfile", "libsndfile") if k in gen}
    now = _now()
    rows = []
    for aid, e in assets.items():
        pairs = [(e["file"], e["sha256"])]
        if "mono_file" in e:
            pairs.append((e["mono_file"], e["mono_sha256"]))
        for f, sha in pairs:
            full = REL + f
            o = old.get(full)
            row = {"file": full, "sha256": sha, "generator": f"meridian-audio-dsp {gen.get('dsp_version', dsp.DSP_VERSION)}",
                   "model": None, "model_sha256": None, "voice": None, "text": None, "language": None,
                   "licence_model": "procedural", "licence_tools": LICENCE_TOOLS,
                   "created_utc": o["created_utc"] if o and o["sha256"] == sha else now,
                   "tool_versions": dict(versions)}
            row.update(e.get("prov", {}))
            rows.append(row)
    rows.sort(key=lambda r: r["file"])
    return {"files": rows}


def notice(assets: dict) -> str:
    has_voice = any(a.startswith(("vox/", "resp/")) for a in assets)
    lines = [
        "Meridian Fracture - audio asset notice (generated by tools/py/audio, do not edit)",
        "",
        "All sound effects, ambience beds and music in this folder are synthesised procedurally by the scripts in",
        "tools/py/audio from a fixed random seed. No recordings and no third-party samples are included.",
        "Licence of the generated audio: procedural (project licence).",
        "",
        "Build-time tools (not shipped): numpy (BSD-3-Clause), soundfile (BSD-3-Clause), libsndfile (LGPL-2.1),",
        "libvorbis (BSD-3-Clause), Pillow (HPND).",
    ]
    if has_voice:
        lines += [
            "",
            "Announcer and unit-response speech: Kokoro-82M weights and voices (Apache-2.0), kokoro-onnx (MIT),",
            "onnxruntime (MIT). Grapheme-to-phoneme tools espeak-ng / phonemizer-fork and piper-tts are GPL-3.0+ and",
            "were used at build time only; they are neither linked nor shipped and the generated audio is not a",
            "derivative. Voices restricted to non-commercial or personal use (macOS `say`, Piper hfc_male / ryan /",
            "lessac) are never used.",
        ]
    return "\n".join(lines) + "\n"
