#!/usr/bin/env python3
"""Generator and verifier of the fixed-point trig tables (game/src/core/fp_tables.gd).

    tools/py/gen_fp_tables.py            regenerate game/src/core/fp_tables.gd and print the table digests
    tools/py/gen_fp_tables.py --verify   independent oracles (no GDScript involved): re-derive the tables,
                                         compare them with the committed file, and print the digests of the
                                         mul_div / isqrt / atan2+rot oracle streams that tests/core/test_fp.gd pins
    tools/py/gen_fp_tables.py --check    exit 1 unless the committed file equals a fresh generation (CI)

Tables (sim_core 5.1): SIN_Q16[a] = round_half_up(sin(a * 2*pi / 4096) * 65536), a = 0..4095;
ATAN_Q8[i] = round_half_up(atan(i / 1024) * (4096 / (2*pi)) * 256), i = 0..1024.
Computed with `decimal` at 60 digits (sin: Taylor to 1e-55; atan: 6 argument halvings + Taylor), first quadrant
only, mirrored by symmetry. Python stdlib only.
"""
from __future__ import annotations

import argparse
import hashlib
import math
import struct
import sys
from decimal import Decimal, getcontext
from fractions import Fraction
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "game" / "src" / "core" / "fp_tables.gd"

getcontext().prec = 60
PI = Decimal("3.14159265358979323846264338327950288419716939937510582097494")
EPS = Decimal(10) ** -55

EXPECT_SIN = 2046802713
EXPECT_ATAN = 1306073121
# Digests of the oracle streams below. The inputs are defined by this file (SimRng ports); the spec's 1403213809 /
# 853641712 / 3886527727 came from unrecorded inputs and are not reproducible. tests/core/test_fp.gd pins these.
ORACLE_DIGESTS = {"muldiv": 1324223992, "isqrt": 2674672166, "trig": 1666396940}


def round_half_up(x: Decimal) -> int:
    return int((x + Decimal("0.5")).to_integral_value(rounding="ROUND_FLOOR"))


def dsin(x: Decimal) -> Decimal:
    term = x
    total = x
    n = 1
    while abs(term) > EPS:
        term = -term * x * x / ((2 * n) * (2 * n + 1))
        total += term
        n += 1
    return total


def datan(x: Decimal) -> Decimal:
    # atan(x) = 2 * atan(x / (1 + sqrt(1 + x^2))); six halvings, then the alternating Taylor series
    y = x
    for _ in range(6):
        y = y / (1 + (1 + y * y).sqrt())
    term = y
    total = y
    n = 1
    y2 = y * y
    while abs(term) > EPS:
        term = -term * y2
        total += term / (2 * n + 1)
        n += 1
    return total * 64


def gen_tables():
    sin_tab = [0] * 4096
    for a in range(0, 1025):
        sin_tab[a] = round_half_up(dsin(PI * a / 2048) * 65536)
    sin_tab[1024] = 65536
    for a in range(0, 1025):
        sin_tab[2048 - a] = sin_tab[a]
    for a in range(1, 2048):
        sin_tab[2048 + a] = -sin_tab[a]
    sin_tab[2048] = 0
    for a in range(1, 1024):
        sin_tab[4096 - a] = -sin_tab[a]
    k = Decimal(524288) / PI  # (4096 / 2pi) * 256
    atan_tab = [round_half_up(datan(Decimal(i) / 1024) * k) for i in range(1025)]
    return sin_tab, atan_tab


def digest32(vals) -> int:
    if not len(vals):
        return 0xD98C1DD4
    b = struct.pack("<%di" % len(vals), *[wrap32(v) for v in vals])
    d = hashlib.md5(b).digest()
    return d[0] | (d[1] << 8) | (d[2] << 16) | (d[3] << 24)


def wrap32(v: int) -> int:
    return ((v + 0x80000000) & 0xFFFFFFFF) - 0x80000000


def check_tables(s, a) -> None:
    for i in range(4096):
        assert s[i] == s[(2048 - i) & 4095] or i == 0 and s[0] == 0, ("sym1", i)
        assert s[(i + 2048) & 4095] == -s[i], ("sym2", i)
    assert s[0] == 0 and s[1024] == 65536 and s[3072] == -65536 and s[2048] == 0
    err = max(abs(s[i] - math.sin(i * 2 * math.pi / 4096) * 65536) for i in range(4096))
    assert err < 0.5, ("sin accuracy", err)
    err = max(abs(a[i] - math.atan(i / 1024) * (4096 / (2 * math.pi)) * 256) for i in range(1025))
    assert err < 0.5, ("atan accuracy", err)
    assert a[0] == 0 and a[1024] == 131072
    assert (s[1], s[2], s[256], s[512], s[1024], s[3072], s[4095]) == (101, 201, 25080, 46341, 65536, -65536, -101)
    assert (a[1], a[256], a[512], a[1023]) == (163, 40884, 77376, 130990)


def emit(s, a) -> str:
    def block(name, vals):
        lines = ["const %s: PackedInt32Array = [" % name]
        for i in range(0, len(vals), 16):
            chunk = ", ".join(str(v) for v in vals[i:i + 16])
            lines.append("\t" + chunk + ("," if i + 16 < len(vals) else ""))
        lines.append("]")
        return "\n".join(lines)

    head = (
        "class_name FpTables\n"
        "extends RefCounted\n"
        "## GENERATED by tools/py/gen_fp_tables.py -- DO NOT EDIT (regenerate; `--verify` re-derives them independently).\n"
        "## SIN_Q16[a]  = round_half_up(sin(a * 2pi / 4096) * 65536), a = 0..4095.\n"
        "## ATAN_Q8[i]  = round_half_up(atan(i / 1024) * (4096 / 2pi) * 256), i = 0..1024 (ATAN_Q8[1024] = 131072).\n"
        "## Checksum.digest32: SIN_Q16 = %d, ATAN_Q8 = %d (Fp.TABLE_DIGEST_*).\n\n" % (digest32(s), digest32(a))
    )
    return head + block("SIN_Q16", s) + "\n\n" + block("ATAN_Q8", a) + "\n"


# ---------------------------------------------------------------------------------------------------------------
# Independent oracles for --verify. Inputs come from a Python port of SimRng (xorshift128, sim_core 5.2), so the
# same streams are reproducible in GDScript; everything else below is written from the mathematical definition.
# ---------------------------------------------------------------------------------------------------------------
M = 0xFFFFFFFF


def mul32(a, c):
    return (a * c) & M


def smix(z):
    z = mul32(z ^ (z >> 16), 0x85EBCA6B)
    z = mul32(z ^ (z >> 13), 0xC2B2AE35)
    return z ^ (z >> 16)


class Rng:
    def __init__(self, seed):
        lo = seed & M
        hi = (seed >> 32) & M
        st = (lo ^ mul32(hi, 0x9E3779B1)) & M
        lanes = []
        for _ in range(4):
            st = (st + 0x9E3779B9) & M
            lanes.append(smix(st))
        if not any(lanes):
            lanes[0] = 1
        self.s = lanes

    def u32(self):
        s0, s1, s2, s3 = self.s
        t = s0 ^ ((s0 << 11) & M)
        n3 = (s3 ^ (s3 >> 19)) ^ (t ^ (t >> 8))
        self.s = [s1, s2, s3, n3]
        return n3

    def below(self, n):
        return (self.u32() * n) >> 32


def frac_round(q: Fraction, mode: str) -> int:
    fl = q.numerator // q.denominator
    if mode == "trunc":
        return int(q) if q >= 0 else -int(-q)
    if mode == "floor":
        return fl
    if mode == "ceil":
        return -((-q.numerator) // q.denominator)
    rem = q - fl
    if mode == "half_up":
        return fl + 1 if rem >= Fraction(1, 2) else fl
    # half_away
    if q >= 0:
        return fl + 1 if rem >= Fraction(1, 2) else fl
    r2 = -q
    f2 = r2.numerator // r2.denominator
    return -(f2 + 1) if (r2 - f2) >= Fraction(1, 2) else -f2


def oracle_muldiv() -> int:
    rng = Rng(1001)
    out = []
    for i in range(60000):
        d0, d1, d2 = rng.u32(), rng.u32(), rng.u32()
        if i % 2 == 0:
            a, b, c = d0 % 2001 - 1000, d1 % 2001 - 1000, d2 % 101 - 50
            if c == 0:
                c = 7
        else:
            a, b, c = (d0 >> 1) - 1073741824, (d1 >> 1) - 1073741824, (d2 & 0xFFFFF) - 524288
            if c == 0:
                c = 1
        q = Fraction(a * b, c)
        for mode in ("trunc", "floor", "ceil", "half_up", "half_away"):
            r = frac_round(q, mode)
            out.append(wrap32(r & M))
            out.append(wrap32((r >> 32) & M))
    return digest32(out)


def oracle_isqrt() -> int:
    rng = Rng(2002)
    out = []
    for _ in range(100000):
        hi, lo, sh = rng.u32(), rng.u32(), rng.u32()
        v = (((hi & 0x3FFFFFFF) << 32) | lo) >> (sh % 63)
        r = math.isqrt(v)
        out.append(wrap32(r & M))
    return digest32(out)


def oracle_trig(sin_tab, atan_tab) -> int:
    def atan_ratio(mn, mx):
        t = (mn << 16) // mx
        if t >= 65536:
            return 512
        i, f = t >> 6, t & 63
        a0 = atan_tab[i]
        return (a0 + (((atan_tab[i + 1] - a0) * f) >> 6) + 128) >> 8

    def atan2(dy, dx):
        if dx == 0 and dy == 0:
            return 0
        ax, ay = abs(dx), abs(dy)
        a = atan_ratio(ay, ax) if ay <= ax else 1024 - atan_ratio(ax, ay)
        if dx >= 0:
            return a if dy >= 0 else (4096 - a) & 4095
        return (2048 - a) if dy >= 0 else (2048 + a)

    rng = Rng(3003)
    out = []
    worst = 0.0
    for _ in range(50000):
        dx = (rng.u32() & 0x7FFFF) - 262144
        dy = (rng.u32() & 0x7FFFF) - 262144
        a = rng.u32() & 4095
        s, c = sin_tab[a], sin_tab[(a + 1024) & 4095]
        t = atan2(dy, dx)
        if dx or dy:
            exact = (math.atan2(dy, dx) * 4096 / (2 * math.pi)) % 4096
            d = abs(t - exact)
            worst = max(worst, min(d, 4096 - d))
        out.extend([t, (dx * c - dy * s + 32768) >> 16, (dx * s + dy * c + 32768) >> 16])
    assert worst <= 1.0, ("atan2 accuracy", worst)
    return digest32(out)


def oracle_rng_vectors() -> None:
    vec = {0: [2407135599, 70998536, 3162094942, 2962270859], 1: [3898016280, 503430273, 2109199260, 1781707058],
           12345: [1165108165, 1674106077, 2795167292, 40330380],
           4294967296: [3443646874, 3280564437, 988752536, 1060094022],
           1234567890123456789: [1222558724, 1588512357, 1375524028, 485886740]}
    for seed, want in vec.items():
        r = Rng(seed)
        assert [r.u32() for _ in want] == want, ("SimRng vector", seed)


def read_committed():
    text = OUT.read_text()
    vals = {}
    for name in ("SIN_Q16", "ATAN_Q8"):
        start = text.index("const %s: PackedInt32Array = [" % name)
        body = text[text.index("[", start) + 1:text.index("]", start)]
        vals[name] = [int(x) for x in body.replace("\n", " ").replace("\t", " ").split(",") if x.strip()]
    return vals["SIN_Q16"], vals["ATAN_Q8"]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--verify", action="store_true")
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    s, a = gen_tables()
    check_tables(s, a)
    ds, da = digest32(s), digest32(a)
    print("SIN_Q16 digest  %d" % ds)
    print("ATAN_Q8 digest  %d" % da)
    if (ds, da) != (EXPECT_SIN, EXPECT_ATAN):
        print("FAIL: table digests differ from Fp.TABLE_DIGEST_SIN/ATAN (%d / %d)" % (EXPECT_SIN, EXPECT_ATAN))
        return 1
    if args.check or args.verify:
        cs, ca = read_committed()
        if (cs, ca) != (s, a):
            print("FAIL: %s differs from a fresh generation" % OUT)
            return 1
        print("committed fp_tables.gd == fresh generation")
    if args.verify:
        oracle_rng_vectors()
        print("SimRng seed vectors (port) OK")
        got = {"muldiv": oracle_muldiv(), "isqrt": oracle_isqrt(), "trig": oracle_trig(s, a)}
        for k, v in got.items():
            print("oracle %-7s digest %d" % (k, v))
        bad = [k for k, v in got.items() if ORACLE_DIGESTS[k] != v]
        if bad:
            print("FAIL: oracle digests differ from ORACLE_DIGESTS for %s" % bad)
            return 1
        print("VERIFY OK")
        return 0
    if args.check:
        return 0
    OUT.write_text(emit(s, a))
    print("wrote %s" % OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
