#!/usr/bin/env python3
"""Slice the generated bible reading view into per-faction digests.

Input : Input/meridian_agent_reference/meridian_factions.md  (generated view of the canonical JSON)
Output: docs/factions/_shared.md      rules, conventions, building registry, service units,
                                      selector registry, campaign fault lines, priorities
        docs/factions/<code>.md       one verbatim faction section (traits, vanilla tree, research,
                                      powers, superweapon, three subfactions with deltas and
                                      resolved combat trees)

The slices are verbatim copies (no interpretation), so per-faction agents can load exactly one file
instead of the whole 200 KB document. Re-run after the bible changes. Stdlib only, deterministic.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRC = ROOT / "Input" / "meridian_agent_reference" / "meridian_factions.md"
OUT = ROOT / "docs" / "factions"

FACTION_RE = re.compile(r"^## faction\.([a-z]+) \| (.+)$")
H2_RE = re.compile(r"^## ")

HEADER = (
    "<!-- GENERATED by tools/py/split_bible_md.py from Input/meridian_agent_reference/meridian_factions.md."
    " Verbatim slice; do not edit. -->\n\n"
)


def main() -> int:
    lines = SRC.read_text(encoding="utf-8").splitlines(keepends=True)
    # Locate every level-2 heading.
    marks = [(i, l) for i, l in enumerate(lines) if H2_RE.match(l)]
    factions: dict[str, tuple[int, int, str]] = {}
    shared_ranges: list[tuple[int, int]] = []
    first_faction_idx = None
    for n, (i, l) in enumerate(marks):
        end = marks[n + 1][0] if n + 1 < len(marks) else len(lines)
        m = FACTION_RE.match(l.rstrip("\n"))
        if m:
            factions[m.group(1)] = (i, end, m.group(2))
            if first_faction_idx is None:
                first_faction_idx = i
        else:
            shared_ranges.append((i, end))
    if len(factions) != 8:
        print(f"expected 8 factions, found {len(factions)}", file=sys.stderr)
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    # Shared: everything before the first faction (title, setting, roster index, rules, conventions,
    # registries, service units) plus everything after the last faction section.
    last_end = max(e for (_, e, _) in factions.values())
    shared = "".join(lines[:first_faction_idx]) + "\n" + "".join(lines[last_end:])
    (OUT / "_shared.md").write_text(HEADER + shared, encoding="utf-8")
    for code, (s, e, name) in sorted(factions.items()):
        body = "".join(lines[s:e]).rstrip() + "\n"
        (OUT / f"{code}.md").write_text(HEADER + body, encoding="utf-8")
        print(f"{code}: {name}: {e - s} lines")
    print(f"shared: {first_faction_idx + len(lines) - last_end} lines")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
